### ISSUE TITLE
Loss of access to Hass-Custom-Alarm web UI

### ISSUE THREAD

**Issue by twistedr34** [akasma74/Hass-Custom-Alarm#106]
**The component:**
 - Current version: 1.12.6
 - Last known working version (if any): N/A

**Your setup:**
 - Home Assistant version: 0.112.2
 - Last known working Home Assistant version (if any): N/A
 - OS: Ubuntu (64bit) on Virtual Box VM
 - Browser name & version: Google Chrome 83.0.4103.116 (Official Build) (64-bit)

**Describe the bug**
Whenever modifying /config/resources/bwalarm/bwalarm.yaml to add "name: Home Alarm" i lose access to the Alarm web interface and instead am greeted with the below screen shot, one thing i notice is that for the version it says "This integration: v1.12.4" even though i am on "v1.12.6". 

**Troubleshooting done**
I have cleared cache and cookies, reinstalled, reloaded old snapshots of home assistant and installed from there but still get same message when adding "Name: Home Alarm" or any name for that matter. 

**To Reproduce**

**Expected behavior**
I would be able to go to the Alarm side panel and modify settings, view logs, arm/disarm system

**Your bwalarm.yaml**
```
platform: bwalarm
panel:
  cameras: []
  panel_title: ''
  camera_update_interval: ''
  hide_passcode: true
  hide_sidebar: true
  enable_sensors_panel: true
enable_night_mode: false
states:
  armed_away:
    immediate:
    - binary_sensor.basement_door
    - binary_sensor.front_door
    - binary_sensor.garage_door
    - binary_sensor.left_basement_window
    - binary_sensor.living_room_door
    - binary_sensor.right_basement_window
    delayed: []
    override: []
    pending_time: '60'
    warning_time: 0
    trigger_time: 600
  armed_home:
    immediate:
    - binary_sensor.basement_door
    - binary_sensor.front_door
    - binary_sensor.garage_door
    - binary_sensor.left_basement_window
    - binary_sensor.living_room_door
    - binary_sensor.right_basement_window
    delayed: []
    override: []
    pending_time: 0
    warning_time: 0
    trigger_time: 600
  armed_night:
    immediate: []
    delayed: []
    override: []
    pending_time: 0
    warning_time: 0
    trigger_time: 600
users:
- id: 727a46afc0194920b506dd87fb3d08b7
  name: ipad
  enabled: true
  code: 'removed'
  picture: ha.png
enable_persistence: true
code: 'removed'
panic_code: 'removed'
mqtt:
  enable_mqtt: true
  override_code: false
  command_topic: home/alarm/cmd
  pending_on_warning: false
  state_topic: home/alarm/state
  payload_arm_home: arm_home
  payload_arm_night: arm_night
  payload_disarm: disarm
  payload_arm_away: arm_away
  qos: 0
```
**Home Assistant log**
No information in log generated

**Additional context**
The only way the web UI works for me is if i remove "name: Home Alarm"  line completely from my bwalarm.yaml file and use the default value of "house". Also issue happens if i put "name: house". Does not matter what i put as long as that line is in the bwalarm.yaml file i will get the error when accessing the web UI.
