### ISSUE TITLE
Unable to arm/disarm ADT Pulse alarm

### ISSUE THREAD

**Issue by twistedr34** [akasma74/Hass-Custom-Alarm#107]
**The component:**
 - Current version: 1.12.6
 - Last known working version (if any): N/A

**Your setup:**
 - Home Assistant version: 0.112.2
 - Last known working Home Assistant version (if any): N/A
 - OS: Ubuntu (64bit) on Virtual Box VM
 - Browser name & version: Google Chrome 83.0.4103.116 (Official Build) (64-bit)

**Describe the bug**
I am unable to arm or disarm the alarm neither from the web UI or the native alarm control panel in lovelace. I have tried using both MQTT via ADT Pulse MQTT and without but neither works for arming/disarming the system. 

**To Reproduce**

**Expected behavior**
Alarm would be armed or disarmed it armed via alternative method (ADT Pulse app on phone, wall control panel)

**Your bwalarm.yaml**
```
platform: bwalarm
panel:
  cameras: []
  panel_title: ''
  camera_update_interval: ''
  hide_passcode: true
  hide_sidebar: true
  enable_sensors_panel: true
enable_night_mode: false
states:
  armed_away:
    immediate:
    - binary_sensor.basement_door
    - binary_sensor.front_door
    - binary_sensor.garage_door
    - binary_sensor.left_basement_window
    - binary_sensor.living_room_door
    - binary_sensor.right_basement_window
    delayed: []
    override: []
    pending_time: '60'
    warning_time: 0
    trigger_time: 600
  armed_home:
    immediate:
    - binary_sensor.basement_door
    - binary_sensor.front_door
    - binary_sensor.garage_door
    - binary_sensor.left_basement_window
    - binary_sensor.living_room_door
    - binary_sensor.right_basement_window
    delayed: []
    override: []
    pending_time: 0
    warning_time: 0
    trigger_time: 600
  armed_night:
    immediate: []
    delayed: []
    override: []
    pending_time: 0
    warning_time: 0
    trigger_time: 600
users:
- id: 727a46afc0194920b506dd87fb3d08b7
  name: ipad
  enabled: true
  code: 'removed'
  picture: ha.png
enable_persistence: true
code: 'removed'
panic_code: 'removed'
mqtt:
  enable_mqtt: true
  override_code: false
  command_topic: home/alarm/cmd
  pending_on_warning: false
  state_topic: home/alarm/state
  payload_arm_home: arm_home
  payload_arm_night: arm_night
  payload_disarm: disarm
  payload_arm_away: arm_away
  qos: 0
```
**Home Assistant log**
No information is generated in log

**Additional context**
I am able to arm/disarm the system when using ADT Pulse MQTT v2.3.0 with the following settings in configuration.yaml file

```
alarm_control_panel: #!include resources/bwalarm/bwalarm.yaml
  - platform: mqtt
    name: "Home Alarm"
    state_topic: "home/alarm/state"
    command_topic: "home/alarm/cmd"
    payload_arm_home: "arm_home"
    payload_arm_away: "arm_away"
    payload_disarm: "disarm"
```

ADT Pulse MQTT Configuration (v2.3.0)

```
ssl: false
certfile: fullchain.pem
keyfile: privkey.pem
pulse_login:
  username: removed
  password: removed
mqtt_host: core-mosquitto
mqtt_url: ''
mqtt_connect_options:
  username: removed
  password: removed
alarm_state_topic: home/alarm/state
alarm_command_topic: home/alarm/cmd
zone_state_topic: adt/zone
smartthings_topic: smartthings
smartthings: false
```
