### ISSUE TITLE
Alarm Panel Card: states buttons not working

### ISSUE THREAD

**Issue by MagaliDB** [akasma74/Hass-Custom-Alarm#122]
**The component:**
 - Current version: v 1.12.4
 - Last known working version (if any): /

**Your setup:**
 - Home Assistant version: v 0.114.4
 - Last known working Home Assistant version (if any): v 0.114.4
 - OS: Windows 10 64-bit
 - Browser name & version: Chrome v 84.0.4147.135

**Describe the bug**

In the left menu, the alarm works perfect and does what it should do. When I add an Alarm Panel Card in the overview, at first glance it seems to be in working order. When I arm the alarm through the Alarm page in the left menu, then go to my overview to see the lovelace card, it will show the keypad and I can diarm the alarm. After disarming the alarm through the lovelace card, it will show me the state buttons (arm home, arm away, arm night) and hide the keypad. But when I want to use any of these state buttons, it won't do anything. I can't arm the alarm through the lovelace card on my overview. Disarming works though, so I can't quite figure out where it's going wrong. 

**To Reproduce**
1. Go to 'Alarm' in the left side menu and arm the alarm
2. Click on 'Overview' in the left side menu
3. In an existing (or new) lovelace card of the type 'Alarm Panel Card', you will now see the keypad
4. Enter the code to disarm the alarm
5. Keypad will disappear and buttons "ARM HOME", "ARM AWAY" and "ARM NIGHT" will appear
6. Pressing any of those buttons will do nothing, no alarm is being armed

**Expected behavior**

I expect the state buttons in the card to arm my alarm.

**Your bwalarm.yaml**

```
platform: bwalarm
panel:
  hide_sidebar: true
  round_buttons: 'True'
  enable_sensors_panel: enable
  enable_fahrenheit: '0'
  panel_title: Home
  hide_sensors: 'True'
  hide_passcode: 'True'
  enable_clock: false
  cameras: []
  enable_floorplan_panel: 'False'
  enable_camera_panel: 'True'
  camera_update_interval: ''
  enable_clock_12hr: 'False'
  enable_weather: false
enable_night_mode: true
states:
  armed_away:
    immediate:
    - binary_sensor.sliding_door
    - binary_sensor.back_door
    delayed:
    - binary_sensor.front_door
    override: []
    pending_time: 40
    warning_time: 60
    trigger_time: 300
  armed_home:
    immediate: []
    delayed:
    - binary_sensor.sliding_door
    - binary_sensor.back_door
    - binary_sensor.front_door
    override: []
    pending_time: '5'
    warning_time: '60'
    trigger_time: 15
  armed_night:
    immediate:
    - binary_sensor.sliding_door
    - binary_sensor.back_door
    - binary_sensor.front_door
    delayed: []
    override: []
    pending_time: 0
    warning_time: 0
    trigger_time: 600
admin_password: !secret alarm_admin_passwd
enable_persistence: true
enable_log: true
code: !secret alarm_code
panic_code: !secret panic_code
passcode_attempts: '5'
passcode_attempts_timeout: '300'
themes:
- name: aaa
  warning_color: '#995BFF'
  pending_color: '#FF2943'
  disarmed_color: '#FF22E6'
  triggered_color: '#FF0000'
  armed_home_color: '#C1B1FF'
  armed_away_color: '#FF8686'
  armed_perimeter_color: '#DAFF9E'
  active: false
  action_button_border_color: '#3ED5FF'
code_to_arm: false
users:
- id: 11faba50c6be4045b4cf9c62992583e5
  name: Hass.io
  enabled: false
  code: 11faba50c6be4045b4cf9c62992583e5
  picture: ha.png
- id: f3035ee406494606b05a8f37ecbb717e
  name: Magamich
  enabled: false
  code: f3035ee406494606b05a8f37ecbb717e
  picture: ha.png
- id: 21e6311c467b4936a7f6e7e9efcc9747
  name: Home Assistant Cast
  enabled: false
  code: 21e6311c467b4936a7f6e7e9efcc9747
  picture: ha.png
- id: cd8a55ac5ee2494b90e0f901c4cad5f6
  name: Michaël
  enabled: false
  code: cd8a55ac5ee2494b90e0f901c4cad5f6
  picture: ha.png
- id: 38c7be44a151454ba9839d02e4e9ee80
  name: USER_MQTT
  enabled: false
  code: 38c7be44a151454ba9839d02e4e9ee80
  picture: ha.png
- id: a3f51b85a0ef4400bfec282d413df986
  name: Home Assistant Cloud
  enabled: false
  code: a3f51b85a0ef4400bfec282d413df986
  picture: ha.png
- id: c6e61e0feea64b5e855fee562bc123b8
  name: Magali
  enabled: false
  code: c6e61e0feea64b5e855fee562bc123b8
  picture: ha.png

```
**Screenshots**

The buttons in the screenshot below do nothing:
![image](https://user-images.githubusercontent.com/64843383/91863525-8085d180-ec6f-11ea-8644-4dbbf187f5bf.png)
Whereas the buttons in the screenshot below work as expected:
![image](https://user-images.githubusercontent.com/64843383/91864383-6c8e9f80-ec70-11ea-81a5-0dbef23dcada.png)
