### ISSUE TITLE
armed_away sensors in override list not triggering alarm

### ISSUE THREAD

**Issue by jcooper-korg** [akasma74/Hass-Custom-Alarm#123]
- Current version: 1.12.6

**Your setup:**
 - Home Assistant version: 0.114.3 on HassOS 4.13

**Describe the bug**
The sensors listed under override are supposed to be ignored while arming, and then trigger the alarm if signaled while it is armed, but they do not trigger.

My armed_away state is set up as follows:
```
states:
  armed_away:
    immediate:
    - binary_sensor.glass_break_kitchen
    - binary_sensor.glass_break_other
    - binary_sensor.kitchen_sink_window
    - binary_sensor.kitchen_table_window
    - binary_sensor.living_room_window
    - binary_sensor.master_bath_window
    - binary_sensor.master_bedroom_window
    - binary_sensor.side_garage_door
    - binary_sensor.office_window
    - binary_sensor.hall_smoke
    delayed:
    - binary_sensor.back_door
    - binary_sensor.front_door
    - binary_sensor.garage_door
    override:
    - binary_sensor.living_room_motion
    - binary_sensor.hall_motion
    pending_time: 60
    warning_time: 30
    trigger_time: 600
```

The override sensors (binary_sensor.living_room_motion  and hall_motion) are working properly, and I can see that when the alarm is armed, they still show proper activity, but the alarm is not triggered.  You can see in this log that after arming the alarm for away, the motion detectors don't trigger the alarm, but opening the master_bath_window triggers it.

```
7:16:18 PM
Alarm Disarmed Automation has been triggered
7:16:18 PM
House changed to disarmed (John Cooper)
7:16:17 PM
Living Room Motion detected motion
7:16:16 PM
Master Bath Window is closed
7:16:15 PM
Siren turned on
7:16:15 PM
Living Room Motion cleared (no motion detected)
7:16:14 PM
Alarm Triggered Automation has been triggered
7:16:14 PM
House changed to triggered
7:16:14 PM
Master Bath Window is opened
7:16:12 PM
Hall Motion cleared (no motion detected)
7:16:12 PM
Living Room Motion detected motion
7:16:08 PM
Hall Motion detected motion
7:16:07 PM
Living Room Motion cleared (no motion detected)
7:16:04 PM
Hall Motion cleared (no motion detected)
7:16:04 PM
Living Room Motion detected motion
7:15:40 PM
Hall Motion detected motion
7:15:31 PM
Red LED turned on
7:15:30 PM
Green LED turned off
7:15:30 PM
Beep turned off
7:15:30 PM
Alarm Armed Automation has been triggered
7:15:30 PM
House changed to armed_away
```

**Expected behavior**
The override sensors should trigger the alarm when armed.
