### ISSUE TITLE
Alarm config page missing from side menu

### ISSUE THREAD

**Issue by MagaliDB** [akasma74/Hass-Custom-Alarm#128]
**The component:**
 - Current version: v 1.12.7
 - Last known working version (if any): c1.12.4

**Your setup:**
 - Home Assistant version: v 0.117.6
 - Last known working Home Assistant version (if any): v 0.114.4
 - OS: Windows 10 64-bit
 - Browser name & version: Chrome v 86.0.4240.75

**Describe the bug**

In the lovelace interface, the default Alarm Panel Card works. However, I can no longer access the Alarm page in the left menu. So I can't use the bwalarm config page. I've reinstalled it through hacs, restarted my HA, but still missing from the left menu.

**Your bwalarm.yaml**

```
platform: bwalarm
panel:
  hide_sidebar: 'False'
  round_buttons: 'False'
  enable_sensors_panel: enable
  enable_fahrenheit: '0'
  panel_title: Home
  hide_sensors: 'True'
  hide_passcode: 'True'
  enable_clock: 'False'
  cameras: []
  enable_floorplan_panel: 'False'
  enable_camera_panel: 'True'
  camera_update_interval: ''
  enable_clock_12hr: 'False'
  enable_weather: 'False'
  enable_serif_font: false
  enable_custom_panel: 'False'
  shadow_effect: false
enable_night_mode: true
states:
  armed_away:
    immediate:
    - binary_sensor.sliding_door
    - binary_sensor.back_door
    delayed:
    - binary_sensor.front_door
    override: []
    pending_time: 40
    warning_time: 60
    trigger_time: 300
  armed_home:
    immediate: []
    delayed:
    - binary_sensor.sliding_door
    - binary_sensor.back_door
    - binary_sensor.front_door
    override: []
    pending_time: '5'
    warning_time: '60'
    trigger_time: 15
  armed_night:
    immediate:
    - binary_sensor.sliding_door
    - binary_sensor.back_door
    - binary_sensor.front_door
    delayed: []
    override: []
    pending_time: 0
    warning_time: 0
    trigger_time: 600
admin_password: !secret alarm_admin_passwd
enable_persistence: true
enable_log: true
code: !secret alarm_code
panic_code: !secret panic_code
passcode_attempts: '5'
passcode_attempts_timeout: '300'
themes: []
code_to_arm: false
users:
- id: 11faba50c6be4045b4cf9c62992583e5
  name: Hass.io
  enabled: false
  code: 11faba50c6be4045b4cf9c62992583e5
  picture: ha.png
- id: f3035ee406494606b05a8f37ecbb717e
  name: Magamich
  enabled: false
  code: f3035ee406494606b05a8f37ecbb717e
  picture: ha.png
- id: 21e6311c467b4936a7f6e7e9efcc9747
  name: Home Assistant Cast
  enabled: false
  code: 21e6311c467b4936a7f6e7e9efcc9747
  picture: ha.png
- id: cd8a55ac5ee2494b90e0f901c4cad5f6
  name: godelieve
  enabled: true
  code: 'omitted'
  picture: ''
- id: 38c7be44a151454ba9839d02e4e9ee80
  name: USER_MQTT
  enabled: false
  code: 38c7be44a151454ba9839d02e4e9ee80
  picture: ha.png
- id: a3f51b85a0ef4400bfec282d413df986
  name: Home Assistant Cloud
  enabled: false
  code: a3f51b85a0ef4400bfec282d413df986
  picture: ha.png
- id: c6e61e0feea64b5e855fee562bc123b8
  name: magali
  enabled: true
  code: 'omitted'
  picture: ha.png

```
