### ISSUE TITLE
Trigger seems to fail with virtual sensor (platform template)

### ISSUE THREAD

**Issue by Extreme79** [akasma74/Hass-Custom-Alarm#68]
**Your components (from Alarm/Settings/About):**
 - v1.11.1

**Platform & Browser:**
 - Hassio (latest available stable channel) on ubuntu 19.10 (Virtual machine)
 - latest chrome

**Describe the bug**
virtual sensor seems do not trigger the alarm.
For testing pourposes (not physical devices yet) I created 2 virtual switches (input boolean), "virtual door" and "virtual siren", and a virtual door sensor. 
Virtual door sensor added to the alarm.
With off virtual door switch the door sensor is closed, with on virtual switch the door sensor is opened.

**Expected behavior**
I expect an alarm trigger when manually turning the virtual door switch on.
This not happen.

```
input_boolean:
  virtual_door:
    name: switch Porta
    initial: off
    icon: mdi:door
  virtual_siren:
    name: Sirena Virtuale
    initial: off
    icon: mdi:eye

sensor:    
- platform: template
  sensors:
    virtual_door_sensor:
      value_template: >
        {{ 'opened' if is_state('input_boolean.virtual_door', 'on')
           else 'closed' }}
      friendly_name: 'Porta virtuale'
```
I'm wrong in something or it's really a bug?
Has to set on and off for teh sensor value? true/false?
