### ISSUE TITLE
mqtt: True is an invalid option

### ISSUE THREAD

**Issue by danobot** [akasma74/Hass-Custom-Alarm#8]
**Describe the bug**
Guide mentions mqtt: True, adding this under `mqtt:` results in a config validation error.

Invalid config for [alarm_control_panel.bwalarm]: [mqtt] is an invalid option for [alarm_control_panel.bwalarm]. Check: alarm_control_panel.bwalarm->mqtt->mqtt. (See ?, line ?). Please check the docs at https://home-assistant.io/components/alarm_control_panel.bwalarm/

**Comment by akasma74** [comment]
> Guide mentions mqtt: True, adding this under `mqtt:` results in a config validation error.

could you be more specific and provide a link to the guide and an appropriate snippet of your alarm.yaml?

**Comment by danobot** [comment]
In the configuration guide:
https://github.com/akasma74/Hass-Custom-Alarm/blob/master/guidance/configuration.md#mqtt-related
```
mqtt:
    mqtt: True
```

tried the following too:
```
mqtt: True
```

**Comment by akasma74** [comment]
Oh, I see. It's just typo, should be `enable_mqtt` inside top-level `mqtt` section, something like this:
```
mqtt:
  enable_mqtt: false
  payload_arm_away: ARM_AWAY
  payload_arm_night: ARM_NIGHT
  override_code: false
  state_topic: home/alarm
  payload_disarm: DISARM
  command_topic: home/alarm/set
  qos: 0
  pending_on_warning: false
  payload_arm_home: ARM_HOME
```

Fixed in docs
